### ISSUE TITLE
Data too long for column 'two_factor_last_challenged'

### ISSUE THREAD

**Issue by sheldonkotyk** [mitydigital/statamic-two-factor#1]
Brand new install of statamic-two-factor v1.1.0
Statamic | 4.21.0

Setting up 2fa for my user I can scan the QR code but when trying to input the ID to finish the setup I get

update `users` set `two_factor_last_challenged` = eyJpdiI6IkUxdjJxRE43V0tkR2h4N3o5eGExbEE9PSIsInZhbHVlIjoiOHNTV21qMWo4dG9tVXFsenF2SHcvWTZLbVg2MENubVVaYkxhM0ZBdVB4aUtPZStIZlVQbTQybjdmNGx3TDhiK2hGcnlZd0VqZVh4WTk2azZlS3ROM2F6QmhKV05ZczQ2QlhWZnZlY0RBNENwb3FEMCtTMTF5ZTlxU3ZlQXRlcjd1Zit2d2pIelhkbjNXRjRWWGRmWTNXcmtFVUp4dHhUQTZQcTBOdkJWeWVZYytKcWJwcFY3TmRuQjRkK0NtSGNXIiwibWFjIjoiOTE1OGJmMDI3M2U2ZWQ3NDA0M2YxNDQwODYxZmM3MjNkYjE2YWI1NGUwZDVmMWRmYjZkMTk3NDYwOGM0NDdjNiIsInRhZyI6IiJ9, `users`.`updated_at` = 2023-09-11 01:09:53 where `id` = 77e5337c-e88a-4bc7-bb28-282a91f093aa

update `users` set `two_factor_last_challenged` = REALLY LONG STRING, `users`.`updated_at` = 2023-09-11 01:09:53 where `id` = MYUUID

I tried a few more and was getting upwards of 420 characters to go in that field. Changing the column to text instead of string solves the problem. I'm just not sure if that is the solution you'd want.

**Comment by martyf** [comment]
Thanks Sheldon, using the DB driver for users I assume?

**Comment by martyf** [comment]
v1.1.1 rectifies this - for your migration, simply use `text` as you've done.

**Comment by sheldonkotyk** [comment]
Yup

**Comment by martyf** [comment]
v1.1.1 rectifies this - for your migration, simply use text as you've done.
