### ISSUE TITLE
QR code not working

### ISSUE THREAD

**Issue by Oleafeon** [mitydigital/statamic-two-factor#13]
Whenever i try to scan the code with google authenticator or authenticator app of microsoft the qr code does not work and i have to set it up via the text code

**Comment by martyf** [comment]
Will look in to this, stay tuned.

**Comment by martyf** [comment]
A fix has been merged, and will be released shortly. 

Out of curiosity, are you using Dark Mode and having it fail?

**Comment by martyf** [comment]
This should be resolved in 2.2.1. Please retry, and also let me know if you were using Dark Mode prior to this release.

**Comment by Oleafeon** [comment]
This has been fixed thanks and yes i was using dark mode sorry for the late reply
