### ISSUE TITLE
Feature Idea: Optional Individual Opt-In

### ISSUE THREAD

**Issue by lakkes-ra** [mitydigital/statamic-two-factor#17]
### Bug description

An "individual optional opt-in" could be a nice addition. If I want to have 2FA, I can set it up for my account myself, if I don't want it, I don't. It could be done with routes like /two-factor/setup, where you get the options to set it up. This way each user can choose own their own, like we know it from many web-platforms. 

I know that https://github.com/kind-work/two-fa did this, but it's archived. 

Neither a bug, nor urgent. Just an idea. :) 

### Steps to reproduce

/

### Environment and versions

```yaml
/
```

**Comment by martyf** [comment]
This is something that is being considered, stay tuned.

**Comment by martyf** [comment]
This is a bit of a slippery one as it can change just how far you go. Love to hear your two cents on an idea.

What could be useful is having a few options:
- all, enforce for all users
- super, enforce for super users only
- none, optional for all users
- specify the roles that require enforcement (i.e. "admin" requires it but "author" is optional)

This way it finds a smarter balance of who can do what and why based on different setups. Thoughts?

**Comment by lakkes-ra** [comment]
Hej @martyf,

the options sound very useful to me. `all` and `super` might be the easiest ones, while `none` sounds like the one, where you'd need a way to enable and disable your 2FA. 

For my special case the `none`/`optional` option is the most wanted. 

Specifying individual roles like `admin` would also be a very welcome option, since I know many system that define their admins with custom roles other the the super admin and I think there are cases where it's good to enforce 2FA for those admins due to their rights. 

So – all in all – sounds perfect. Thank you for considering and making thoughts! 🙏

**Comment by martyf** [comment]
It's coming... just the usual chaos at end of year. But my hope is to get to this before the end of the year - apologies for the delay, just want to do it right, not rushed.

**Comment by martyf** [comment]
The hard work is done - and just waiting on some translation strings to come in. I'd like to release it in the next day or so, so failing hearing from translators, will attempt with Google Translate :|

**Comment by martyf** [comment]
2.4.1 has been tagged which introduces opt in.

This only works when you use the `enforced_roles` config property. 

Users who are not included by enforcing a role (or `enforced_roles` is an empty array - meaning no role is enforced) now have the option to opt in to Two Factor.

Note that super users are always enforced, regardless.

**Comment by lakkes-ra** [comment]
Thank you for your work @martyf!
