### ISSUE TITLE
Wrong Status on Index

### ISSUE THREAD

**Issue by FabioWidmer** [mitydigital/statamic-two-factor#2]
Thanks for creating this package! I bought it and am currently using it in a new project. There are a two issues I noticed:

- On the index page it always says "Not set up" (Eloquent User DB)
- Some texts are not translated

I have as well translated the language files to Swiss German. If there is interest I can make a PR and add it here officially.

**Comment by martyf** [comment]
Thanks for this - I'll get these two points fixed up today or tomorrow. When I've updated the localisation point, a PR for Swiss German would be welcome for sure - I'll have to hit you up for any further translations though ;) Perhaps hang tight until I've gone through all strings before doing that. Sound OK to you?

**Comment by martyf** [comment]
I've just tagged 1.1.2 which should address both of these.

Regarding texts not translated, I added three for the Index fieldtype - are there others I've missed that you spotted?

**Comment by martyf** [comment]
Hmmm OK. If you open the JavaScript console, are you seeing any errors?

**Comment by martyf** [comment]
I think this is my bad... for some reason the build JS didn't go to git as expected. Can you please try 1.1.3.

This also has your translations, and a fix for the enter issue on the Challenge view.

**Comment by martyf** [comment]
Hoorah! Glad it is all sorted!
