### ISSUE TITLE
Use 2FA for front-end logins

### ISSUE THREAD

**Issue by JoeriE** [mitydigital/statamic-two-factor#4]
Hi,

Can this plugin also be used for front-end login form? I have a site with some users that can only login on the website and can't access the cms. I would also like to enable 2FA for them.

Best wishes,
Joeri Evers

**Comment by martyf** [comment]
At this stage, this addon is only for CP users. 

Your best beet would be to look in to something more Laravel-based, such as Laravel Fortify or a third-party package.

This is something that could be added but can't give a timeframe at the moment.

**Comment by martyf** [comment]
Closed due to inactivity
