### ISSUE TITLE
Mode is not defined at the login challenge

### ISSUE THREAD

**Issue by christophstockinger** [mitydigital/statamic-two-factor#6]
Hi @martyf ,

I have installed your addon and equipped my account with 2FA via 1Password. Now I want to log in locally again and get the following error: https://flareapp.io/share/V7j9erkP

Do you have any idea what is missing or why the mode is not passed when I send the one-time password in the challenge?

```
Application Name: [LOCAL] Website
Laravel Version: 10.35.0
PHP Version: 8.2.13
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: involveme-cms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single, flare
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 11
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
aerni/font-awesome: 2.0.0
aryehraber/statamic-logbook: 3.1.0
aryehraber/statamic-uuid: 2.2.0
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-documentation: 1.9.0
mitydigital/statamic-two-factor: 1.1.4
rias/statamic-data-import: 1.3.0
rias/statamic-redirect: 3.4.4
statamic/collaboration: 0.7.3
statamic/seo-pro: 5.3.0
swiftmade/statamic-clear-assets: 2.0.0
```

**Comment by martyf** [comment]
That's quite odd, and not something I can replicate.

On the "challenge" screen, when it asks for the code, can you please view source, and send that through?

Around line 30 should be the `x-data` definition for the form, something like:
```html
x-data="{ mode: 'code', code: '', recovery_code: '' }"
```

What does that have in it?

Do you have step-by-step instructions to reliably replicate it every time? i.e. if you go to a private browsing window, does it still occur? 

If you can replicate it 100% of the time, a repo showing this would be awesome if that's possible too.

As a side note, while we're getting to the bottom of this, set `STATAMIC_TWO_FACTOR_ENABLED` to `false` in your env to at least be able to allow you to log in

**Comment by christophstockinger** [comment]
I did some more research myself and tried to find out what the cause was.

In the meantime, I can no longer reproduce this after I manually adjusted the user and removed the fields for 2FA.

However, we have another problem:
But I need to elaborate on that.

We had an existing website with the old 2FA addon. We have replaced this addon with yours.

I was then able to successfully activate 2FA for my user in the local environment when logging in for the first time after installation.

We then deployed the page to our staging environment so that other users can also activate 2FA with the new addon.
However, this is not possible and we receive the following error during setup.
![image](https://github.com/mitydigital/statamic-two-factor/assets/24808473/eaa7aad3-6f90-43c3-ad96-5e0c27eec3bf)

We have also tested this with a newly created user in addition to the existing users and the same problem occurs here.

The APP_KEY is the same both locally and on staging.

As soon as I'm at my MacBook, I'll add the source code of the form as a comment.

**Comment by martyf** [comment]
Just confirming things:

1 - you create a user locally, set up TFA, and that works fine
2 - you deploy to staging, and that user can log in, with TFA, correctly
3 - existing users from the old addon can't set up TFA on staging

Do you have more explicit step-by-step instructions to follow? We've had no issues with user setup on different environments so just not really sure what's going on.

**Comment by christophstockinger** [comment]
All three points are correct.

There are no specific step-by-step instructions.

We installed the addon locally as usual and set up my users accordingly with 2FA.
We deleted the 2FA fields of the old addon for all other users.

We then deployed it to Staging and the setup is not possible for the existing users there. The above error message is always displayed. No matter which user.

**Comment by martyf** [comment]
Are you able to share a repo of the issue? Hard to know what to look at when we're not encountering issues like this so would be good to have a dig around.

**Comment by christophstockinger** [comment]
> Are you able to share a repo of the issue? Hard to know what to look at when we're not encountering issues like this so would be good to have a dig around.

You have an invite

**Comment by martyf** [comment]
This is not an issue of the addon, but an issue with your config.

If you look at the Network tab when loading the screen, you'll see there is a request made to the same route as the actual (HTML) route to try to load styles.

This means that the page loads (correct) and then your `STATAMIC_CUSTOM_CSS_URL` is incorrectly defined, meaning that a second request (incorrect) loads.

But that second request is changing what the user's actual code is - so this is causing the verification to fail.

If I comment that line out of the `env` so there is no custom CSS, there's now only one (correct) request to the server, so works as expected.

Try that and see how you go, but it is definitely something in your app causing this as we use it across multiple (dev, staging and prod) with no issues. But that path in your `env` file doesn't look right to me.

Let me know how you go.

**Comment by christophstockinger** [comment]
@martyf I can confirm your thesis. We have corrected this and it now works

Thank you very much for your help. At some point you become blind. 😉

I'm closing the ticket.
