### ISSUE TITLE
No publishable resources for tag [two-factor-config].

### ISSUE THREAD

**Issue by eleftrik** [mitydigital/statamic-two-factor#9]
Version 1.1.5.

If I run `php artisan vendor:publish --tag=two-factor-config` I got this:

` INFO  No publishable resources for tag [two-factor-config].`

It seems the config file cannot be published. Am I wrong?

Thanks.

**Comment by martyf** [comment]
There is an error in the docs. 

Please use:
```bash
php artisan vendor:publish --tag=statamic-two-factor-config
```

The docs have been updated.
